

import Progress from "../../common/step-progressbar"
import { Inter } from 'next/font/google'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function ClientLayout({ children }) {
  return (
  <>
   <h1 className='mt-5 pt-5'>ansari</h1>
   <Progress />
        {children}
  </>
     
       
        
    
  )
}
