
import { Inter } from 'next/font/google'
import { AuthProvider } from '/src/app/common/auth'
import NextTopLoader from 'nextjs-toploader'
import SwalMessage from './common/swal'
// import './globals.css'
import '/public/css/style.css'
import '/public/css/Layout.css'
import '/public/css/datatable.css'

import 'bootstrap/dist/css/bootstrap.min.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sweet Delight',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true} aria-hidden={true}>

        <AuthProvider>
          <NextTopLoader />
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
