'use client'
import Header from '../common/header'
import Footer from '../common/footer'

import { Inter } from 'next/font/google'
import {usePathname} from 'next/navigation'
// import './globals.css'
import '/public/css/style.css'
import '/public/css/Layout.css'
import '/public/css/datatable.css'

import 'bootstrap/dist/css/bootstrap.min.css';
import CartSidebar from '../common/cart-sidebar'



// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }


export default function ClientLayout({ children }) {
const pathname =  usePathname()
  return  (
    <>
    {pathname !== '/dashboard/checkout' || pathname !== '/dashboard/myCart' ? <CartSidebar />: ''} 
     {pathname !== '/dashboard/checkout' ? <Header />: ''} 
        {children}
        {pathname !== '/dashboard/checkout' ? <Footer />: ''} 
    </>
   
  )
}

